### ISSUE TITLE
RevPiModIO instantiation hangs in external process

### ISSUE THREAD

**Issue by jacoblapenna** [naruxde/revpimodio2#22]
I am trying to create a basic browser application with python flask to show data from the Revolution Pi's AIO module. To do this, I run two python processes, one to run flask and deal with client requests, and another to run the data acquisition cycles. In the main process, use of the revpimodio2 library is straightforward and works fine. However, the `autorefresh` threads must run in the data acquisition process. For this reason, the `RevPiModIO` object must be instantiated in this process. However, doing this makes the process hang.

I made a very basic project on my github to demonstrate with a README for how to run it: https://github.com/jacoblapenna/RevPi_Browser_App.git

With this project, you can see that simply commenting and uncommenting the object instantiation breaks the app.

The stack trace on exiting is:
```
Traceback (most recent call last): 
Exception in thread Thread-3: 
File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner 
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner 
self.run()
File "/home/pi/Prototypes/RevPi_Browser_App/.env/lib/python3.10/site-packages/revpimodio2/helper.py", line 622, in run
self.run()
File "/home/pi/Prototypes/RevPi_Browser_App/.env/lib/python3.10/site-packages/revpimodio2/helper.py", line 622, in run
sleep(self._refresh - mrk_delay)
KeyboardInterrupt
sleep(self._refresh - mrk_delay)
KeyboardInterrupt
```

Though I think this is just where the program happens to be at the time of exit, as I put my own print statement within `helper.py` at line 622 and it is running in a continuous loop. Also, subsequent interrupts show the same trace for more threads until finally exiting the program. Moreover, the python processes are still alive via `$ ps -ef | grep python` after exiting.

I have no idea where it is hanging and no idea how to figure this out. Any suggestions would be greatly appreciated.

**Comment by jacoblapenna** [comment]
The following similar program works however:

```
from multiprocessing import Pipe, Process
import revpimodio2

def process_target(conn):
    class DAQ:
        def __init__(self, conn):
            self._conn = conn
            self._revpi = revpimodio2.RevPiModIO(autorefresh=True)

        def _produce_data(self, ct):
            new_data = self._revpi.io.InputValue_1.value/1000
            self._conn.send(new_data)

        def produce(self):
            self._revpi.cycleloop(self._produce_data, cycletime=25)

    daq = DAQ(conn)
    daq.produce()

conn1, conn2 = Pipe()
p = Process(target=process_target, args=(conn2,))
p.start()

while True:
    if conn1.poll():
        print(conn1.recv())
```

**Comment by naruxde** [comment]
Strange!

There is something with the "eventlet" module... ModIO will create a internal thread if you are using `autorefresh=True`. Something in the eventlet module will do something which wait for the end of the internal ModIO thread... This will never happen. If I remove the eventlet things, we will reach the "never reaches here when above line is not commented out..." line...

Maybe you have to create a own cycle without the autorefresh and internal cycleloop...

I modified your repository for some testing...

**Comment by jacoblapenna** [comment]
Thank you for this. I think it may have to do with the eventlet "monkey patching", which is required to use redis, and redis (or similar) is required to emit from a socket in an external process. If I use the multiprocessing pipe connection to send data to the main process, I don't need redis, and I don't need to monkey patch eventlet, and it works. But this requires a callback from the front end to grab any new data passed through the pipe, which doubles network traffic. Anyway, you gave me a place to narrow my focus. I'll try and get to the bottom of this next week (US time zones)...

**Comment by jacoblapenna** [comment]
It was as simple as putting the eventlet import and monkey patch code at the top of the main script, before any other imports, [as described in the eventlet documentation](https://eventlet.net/doc/patching.html#monkey-patch). The example is working as originally designed, and I've uploaded a more complex example for a browser oscilloscope application [here](https://github.com/jacoblapenna/RevPi_Browser_Osciloscope.git).

I still don't fully understand everything `eventlet.monkey_patch()` is doing, [but it is clear it affects threading](https://stackoverflow.com/questions/12758952/green-threads-and-thread-in-python).

Thanks for your help on this and all the work you have done to make Revolution Pis accessible to Pythonistas!
